//! `scopeon badge` — Generate shields.io badge URLs from local AI stats.
//!
//! Outputs privacy-safe, purely local badge URLs derived from aggregate stats
//! (no prompts, no filenames). Embed these in your README to advertise transparent
//! AI cost tracking and create organic discovery.
//!
//! # Usage
//!
//!   scopeon badge                    # default: Markdown image links
//!   scopeon badge --format url       # bare badge URLs only
//!   scopeon badge --format html      # <img> tags
//!
//! # Output example (Markdown)
//!
//!   ![AI Cost](https://img.shields.io/badge/AI_Cost-%240.43%2Fday-blue?logo=anthropic)
//!   ![Cache](https://img.shields.io/badge/Cache-68%25-brightgreen?logo=anthropic)
//!   ![Powered by Scopeon](https://img.shields.io/badge/AI_Observability-Scopeon-blueviolet)

use anyhow::Result;
use scopeon_core::{cache_hit_rate, Database};

#[derive(Debug, Clone, Copy, PartialEq, clap::ValueEnum)]
pub enum BadgeFormat {
    /// Markdown `![label](url)` image links (default)
    Markdown,
    /// Bare shield URLs, one per line
    Url,
    /// HTML `<img>` tags
    Html,
}

/// Render a shields.io static badge URL.
/// shields.io encoding: `-` → `--`, `_` → `__`, spaces → `_`.
fn badge_url(label: &str, message: &str, color: &str) -> String {
    let encode = |s: &str| {
        s.replace('-', "--")
            .replace('_', "__")
            .replace(' ', "_")
            .replace('/', "%2F")
            .replace('$', "%24")
            .replace('%', "%25")
    };
    format!(
        "https://img.shields.io/badge/{}-{}-{}",
        encode(label),
        encode(message),
        color
    )
}

fn color_for_cost(usd_per_day: f64) -> &'static str {
    if usd_per_day < 0.50 {
        "brightgreen"
    } else if usd_per_day < 2.00 {
        "green"
    } else if usd_per_day < 5.00 {
        "yellow"
    } else if usd_per_day < 15.00 {
        "orange"
    } else {
        "red"
    }
}

fn color_for_cache(pct: u64) -> &'static str {
    if pct >= 80 {
        "brightgreen"
    } else if pct >= 60 {
        "green"
    } else if pct >= 40 {
        "yellow"
    } else if pct >= 20 {
        "orange"
    } else {
        "red"
    }
}

fn format_badge(label: &str, _message: &str, url: &str, fmt: BadgeFormat) -> String {
    match fmt {
        BadgeFormat::Url => url.to_string(),
        BadgeFormat::Markdown => format!("![{label}]({url})"),
        BadgeFormat::Html => format!("<img alt=\"{label}\" src=\"{url}\">"),
    }
}

pub fn run(db: &Database, format: BadgeFormat) -> Result<()> {
    let global = db.get_global_stats()?;
    let rollups = db.get_daily_rollups(30)?;

    // Today's cost (rollups is oldest-first).
    let today_cost = rollups.last().map(|r| r.estimated_cost_usd).unwrap_or(0.0);

    // Overall cache hit rate.
    let cache_pct = (cache_hit_rate(
        global.total_input_tokens,
        global.total_cache_read_tokens,
        global.total_cache_write_tokens,
    ) * 100.0)
        .round() as u64;

    // Badges to generate.
    let badges: Vec<(String, String, &str)> = vec![
        (
            "AI Cost".to_string(),
            format!("${today_cost:.2}/day"),
            color_for_cost(today_cost),
        ),
        (
            "Cache".to_string(),
            format!("{cache_pct}%"),
            color_for_cache(cache_pct),
        ),
        (
            "AI Observability".to_string(),
            "Scopeon".to_string(),
            "blueviolet",
        ),
    ];

    if format == BadgeFormat::Markdown {
        println!("<!-- Scopeon AI observability badges — generated by `scopeon badge` -->");
    }

    for (label, message, color) in &badges {
        let url = badge_url(label, message, color);
        println!("{}", format_badge(label, message, &url, format));
    }

    if format == BadgeFormat::Markdown {
        println!();
        println!("<!-- Update anytime: `scopeon badge >> README.md` or pipe to pbcopy/xclip -->");
    }

    Ok(())
}
